version: '3'
services:
  myapp:
    build:
      context: .
    image: headout-dc
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1500M
